### ISSUE TITLE
Pacote em Desenvolvimento

### ISSUE THREAD

**Issue by TiagoVentura** [Gabriel-Assuncao/POFIBGE#1]
Ola, 

Eu tentei utilizar o pacote seguindo as instrucoes do manual, e encontrei o seguinte erro:

```r
#install.packages("POFIBGE")
#devtools::install_github("Gabriel-Assuncao/POFIBGE")
library(POFIBGE)
dadosPOF <- get_pof(year=2017)
#> The get_pof function is under development and will be available soon in package POFIBGE.
```

Alguma solucao ou outro caminho sugerido para acessar estes dados?

**Comment by Gabriel-Assuncao** [comment]
Prezado Tiago Ventura, boa tarde.

Informamos que o pacote relacionado à POF, no caso o POFIBGE, nos moldes dos pacotes já disponibilizados para PNADC, PNS e PNAD COVID19, está em desenvolvimento e não existe no momento previsão para submissão da versão consolidada. Estamos trabalhando na parte estrutural que envolve esta pesquisa para então disponibilizar a versão funcional do pacote. Caso seja de seu interesse existem disponíveis os pacotes PNADcIBGE, COVIDIBGE e PNSIBGE referentes às demais pesquisas domiciliares amostrais conduzidas pelo IBGE.

Já os microdados da POF 2008-2009 e da POF 2017-2018, juntamente com os programas de leitura em R e SAS (sendo que para a POF 2008-2009 só existe o programa em SAS), estão disponíveis em: https://www.ibge.gov.br/estatisticas/sociais/saude/24786-pesquisa-de-orcamentos-familiares-2.html?=&t=microdados, caso existam dúvidas sobre a utilização de tais programas, indicamos que entre em contato com o canal de atendimento [ibge@ibge.gov.br](mailto:ibge@ibge.gov.br) para que seu atendimento seja direcionado à equipe responsável.
